services:
  questdb:
    image: questdb/questdb:latest
    container_name: questdb
    ports:
      - "9000:9000"
      - "8812:8812"
      - "9009:9009"
    volumes:
      - questdb_data:/var/lib/questdb

  fastapi-api:
    build: .
    container_name: fastapi-api
    depends_on:
      - questdb
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=postgresql://admin:quest@questdb:8812/qdb

volumes:
  questdb_data:
